# Generated by Django 3.2.13 on 2022-12-22 17:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lcks', '0002_player_position'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transfer',
            name='user',
        ),
        migrations.AddField(
            model_name='transfer',
            name='player',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='lcks.player'),
            preserve_default=False,
        ),
    ]
